### ISSUE TITLE
ERROR: (MainThread) list index out of range

### ISSUE THREAD

**Issue by unixfox** [qk4l/zabbix-cachet#7]
Hi I've an error with Zabbix Cachet.

## Description of the error

Zabbix Cachet crash at start with this error:
````
2016-10-14 17:23:23 CEST INFO: (MainThread) Zabbix Cachet v.0.1 started
2016-10-14 17:23:23 CEST INFO: (MainThread) JSON-RPC Server Endpoint: https://monitor.aresrpg.fr/api_jsonrpc.php
2016-10-14 17:23:23 CEST DEBUG: (MainThread) Sending: {
    "jsonrpc": "2.0",
    "id": 0,
    "method": "user.login",
    "params": {
        "password": "xxxxxxxxxxxxxxxxxxxxxxx",
        "user": "bot"
    }
}
2016-10-14 17:23:23 CEST INFO: (MainThread) Starting new HTTPS connection (1): monitor.aresrpg.fr
2016-10-14 17:23:25 CEST DEBUG: (MainThread) "POST /api_jsonrpc.php HTTP/1.1" 200 None
2016-10-14 17:23:25 CEST DEBUG: (MainThread) Response Code: 200
2016-10-14 17:23:25 CEST DEBUG: (MainThread) Response Body: {
    "jsonrpc": "2.0",
    "result": "837e692f7f981cc981791f688301aa04",
    "id": 0
}
2016-10-14 17:23:25 CEST DEBUG: (MainThread) Sending: {
    "jsonrpc": "2.0",
    "id": 1,
    "method": "service.get",
    "params": {
        "selectDependencies": "extend",
        "filter": {
            "name": "Cachet"
        }
    },
    "auth": "xxxxxxxxxxxxxxxx"
}
2016-10-14 17:23:25 CEST DEBUG: (MainThread) "POST /api_jsonrpc.php HTTP/1.1" 200 None
2016-10-14 17:23:25 CEST DEBUG: (MainThread) Response Code: 200
2016-10-14 17:23:25 CEST DEBUG: (MainThread) Response Body: {
    "jsonrpc": "2.0",
    "result": [
        {
            "dependencies": [
                {
                    "soft": "0",
                    "linkid": "1",
                    "serviceupid": "1",
                    "serviceid": "2",
                    "sortorder": "0",
                    "servicedownid": "2"
                }
            ],
            "showsla": "0",
            "goodsla": "99.9000",
            "algorithm": "1",
            "serviceid": "1",
            "sortorder": "0",
            "triggerid": "0",
            "status": "0",
            "name": "Cachet"
        }
    ],
    "id": 1
}
2016-10-14 17:23:25 CEST DEBUG: (MainThread) Sending: {
    "jsonrpc": "2.0",
    "id": 2,
    "method": "service.get",
    "params": {
        "selectDependencies": "extend",
        "serviceids": [
            "2"
        ]
    },
    "auth": "xxxxxxxxxxxxxxxxxxxxxxxxx"
}
2016-10-14 17:23:25 CEST DEBUG: (MainThread) "POST /api_jsonrpc.php HTTP/1.1" 200 None
2016-10-14 17:23:25 CEST DEBUG: (MainThread) Response Code: 200
2016-10-14 17:23:25 CEST DEBUG: (MainThread) Response Body: {
    "jsonrpc": "2.0",
    "result": [
        {
            "dependencies": [],
            "showsla": "0",
            "goodsla": "99.9000",
            "algorithm": "1",
            "serviceid": "2",
            "sortorder": "0",
            "triggerid": "0",
            "status": "0",
            "name": "Plateformes Web publiques"
        }
    ],
    "id": 2
}
2016-10-14 17:23:25 CEST DEBUG: (MainThread) Sending: {
    "jsonrpc": "2.0",
    "id": 3,
    "method": "service.get",
    "params": {
        "selectDependencies": "extend",
        "serviceids": []
    },
    "auth": "xxxxxxxxxxxxxxxxxxxxxxxxxxx"
}
2016-10-14 17:23:25 CEST DEBUG: (MainThread) "POST /api_jsonrpc.php HTTP/1.1" 200 None
2016-10-14 17:23:25 CEST DEBUG: (MainThread) Response Code: 200
2016-10-14 17:23:25 CEST DEBUG: (MainThread) Response Body: {
    "jsonrpc": "2.0",
    "result": [],
    "id": 3
}
2016-10-14 17:23:25 CEST DEBUG: (MainThread) Sending: {
    "jsonrpc": "2.0",
    "id": 4,
    "method": "trigger.get",
    "params": {
        "expandComment": "true",
        "triggerids": "0",
        "expandDescription": "true"
    },
    "auth": "xxxxxxxxxxxx"
}
2016-10-14 17:23:25 CEST DEBUG: (MainThread) "POST /api_jsonrpc.php HTTP/1.1" 200 None
2016-10-14 17:23:25 CEST DEBUG: (MainThread) Response Code: 200
2016-10-14 17:23:25 CEST DEBUG: (MainThread) Response Body: {
    "jsonrpc": "2.0",
    "result": [],
    "id": 4
}
2016-10-14 17:23:25 CEST ERROR: (MainThread) list index out of range
````

I tried to remove and recreate the trigger and the IT service but it still doesn't work.

### My configuration file
````
---
zabbix:
  user: bot
  pass: xxxxxxxxxxxxxxxx
  server: https://monitor.aresrpg.fr
  https-verify: true

cachet:
  token: 'xxxxxxxxxxxxxx'
  server: https://status.aresrpg.fr
  https-verify: true

settings:
  # IT Service which will be a root for Cachet Components
  # Leave it empty if you want to use /
  root_service: 'Cachet'
  # How often check Zabbix for new incidents
  update_inc_interval: 30  # in seconds
  # How often check Zabbix for new IT Services
  update_comp_interval: 30  # in seconds
  # Log level https://docs.python.org/3.4/library/logging.html#levels
  log_level: DEBUG
  # Additional logging level for requests module
  log_level_requests: DEBUG
````

### Screenshots of Cachet and Zabbix
![](http://pix.toile-libre.org/upload/original/1476458884.png)
![](http://pix.toile-libre.org/upload/original/1476458919.png)
![](http://pix.toile-libre.org/upload/original/1476458978.png)
![](http://pix.toile-libre.org/upload/original/1476459021.png)
